#!/bin/bash

ssh zixwang@tlab036.clamv.jacobs-university.de
ssh zixwang@tlab037.clamv.jacobs-university.de
ssh zixwang@tlab038.clamv.jacobs-university.de
ssh zixwang@tlab039.clamv.jacobs-university.de
ssh zixwang@tlab040.clamv.jacobs-university.de
ssh zixwang@tlab041.clamv.jacobs-university.de
ssh zixwang@tlab042.clamv.jacobs-university.de
ssh zixwang@tlab043.clamv.jacobs-university.de
ssh zixwang@tlab044.clamv.jacobs-university.de
ssh zixwang@tlab045.clamv.jacobs-university.de
ssh zixwang@tlab046.clamv.jacobs-university.de
ssh zixwang@tlab047.clamv.jacobs-university.de
ssh zixwang@tlab048.clamv.jacobs-university.de
ssh zixwang@tlab049.clamv.jacobs-university.de
ssh zixwang@tlab050.clamv.jacobs-university.de
ssh zixwang@tlab051.clamv.jacobs-university.de
ssh zixwang@tlab052.clamv.jacobs-university.de
ssh zixwang@tlab053.clamv.jacobs-university.de
ssh zixwang@tlab054.clamv.jacobs-university.de
ssh zixwang@tlab055.clamv.jacobs-university.de
ssh zixwang@tlab056.clamv.jacobs-university.de
ssh zixwang@tlab057.clamv.jacobs-university.de
ssh zixwang@tlab058.clamv.jacobs-university.de
ssh zixwang@tlab059.clamv.jacobs-university.de
ssh zixwang@tlab060.clamv.jacobs-university.de
ssh zixwang@tlab061.clamv.jacobs-university.de
ssh zixwang@tlab062.clamv.jacobs-university.de
ssh zixwang@tlab063.clamv.jacobs-university.de
ssh zixwang@tlab064.clamv.jacobs-university.de
ssh zixwang@tlab065.clamv.jacobs-university.de
ssh zixwang@tlab066.clamv.jacobs-university.de
ssh zixwang@tlab067.clamv.jacobs-university.de
ssh zixwang@tlab068.clamv.jacobs-university.de
ssh zixwang@tlab069.clamv.jacobs-university.de
ssh zixwang@tlab070.clamv.jacobs-university.de
ssh zixwang@tlab071.clamv.jacobs-university.de
